build:
  maxIssues: 0

complexity:
  ComplexCondition:
    active: false
  LongParameterList:
    active: false
  LongMethod:
    active: false
  CyclomaticComplexMethod:
    active: false
  TooManyFunctions:
    active: false

empty-blocks:
  EmptyElseBlock:
    active: false

naming:
  FunctionNaming:
    active: false

style:
  DestructuringDeclarationWithTooManyEntries:
    active: false
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedParameter:
    active: false
